carmapi/config/routes.rb
Rails.application.routes.draw do
  resources :participantes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

carmapi/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

carmapi/app/models/participante.rb
class Participante < ApplicationRecord
end

carmapi/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

carmapi/app/controllers/participantes_controller.rb
class ParticipantesController < ApplicationController
  before_action :set_participante, only: [:show, :edit, :update, :destroy]

  # GET /participantes
  # GET /participantes.json
  def index
    @participantes = Participante.all
  end

  # GET /participantes/1
  # GET /participantes/1.json
  def show
  end

  # GET /participantes/new
  def new
    @participante = Participante.new
  end

  # GET /participantes/1/edit
  def edit
  end

  # POST /participantes
  # POST /participantes.json
  def create
    @participante = Participante.new(participante_params)

    respond_to do |format|
      if @participante.save
        format.html { redirect_to @participante, notice: 'Participante was successfully created.' }
        format.json { render :show, status: :created, location: @participante }
      else
        format.html { render :new }
        format.json { render json: @participante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participantes/1
  # PATCH/PUT /participantes/1.json
  def update
    respond_to do |format|
      if @participante.update(participante_params)
        format.html { redirect_to @participante, notice: 'Participante was successfully updated.' }
        format.json { render :show, status: :ok, location: @participante }
      else
        format.html { render :edit }
        format.json { render json: @participante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participantes/1
  # DELETE /participantes/1.json
  def destroy
    @participante.destroy
    respond_to do |format|
      format.html { redirect_to participantes_url, notice: 'Participante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participante
      @participante = Participante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participante_params
      params.require(:participante).permit(:nome_completo, :data_nascimento, :cidade, :estado, :rg, :cpf, :valor)
    end
end

carmapi/app/helpers/application_helper.rb
module ApplicationHelper
end

carmapi/app/helpers/participantes_helper.rb
module ParticipantesHelper
end

carmapi/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carmapi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

carmapi/app/views/participantes/_form.html.erb
<%= form_for(participante) do |f| %>
  <% if participante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participante.errors.count, "error") %> prohibited this participante from being saved:</h2>

      <ul>
      <% participante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <form class="form-control">
	
  <div class="row">
	  <div class="col-lg-8">
		  <div class="input-group">
		    <%= f.label :nome_completo %>
		    <%= f.text_field :nome_completo, class:"form-control" %>
		  </div>
	  </div>
  </div>

  <div class="row">
	  <div class="col-lg-8">
		  <div class="input-group">
		    <%= f.label :data_nascimento %><br/>
		    <%= f.date_select :data_nascimento, class:"form-control" %>
		  </div>
	  </div>
  </div>

  <div class="row">
	  <div class="col-lg-8">
		  <div class="input-group">
		    <%= f.label :cidade %>
		    <%= f.text_field :cidade , class:"form-control "%>
		  </div>
	  </div>
  </div>
  <div class="row">
	  <div class="col-lg-8">
		  <div class="input-group">
		    <%= f.label :estado %>
		    <%= f.text_field :estado, class:"form-control" %>
		  </div>
	  </div>
  </div>

  <div class="row">
	  <div class="col-lg-8">
		  <div class="input-group">
		    <%= f.label :rg %>
		    <%= f.text_field :rg , class:"form-control"%>
		  </div>
	  </div>
  </div>
  <div class="row">
	  <div class="col-lg-8">
		  <div class="input-group">
		    <%= f.label :cpf %>
		    <%= f.text_field :cpf, class:"form-control" %>
		  </div>
	  </div>
  </div>
  
  <br/>
  <div class="row">
	  <div class="col-lg-8">
		  <div class="input-group">
		    <%= f.submit(class:"btn btn-success") %>
		  </div>
	  </div>
  </div>
<% end %>

</form>

carmapi/app/views/participantes/edit.html.erb
<h1>Editar</h1>

<%= render 'form', participante: @participante %>
<br/>
<%= link_to 'Exibir', @participante, class:"btn btn-primary" %> 
<%= link_to 'Voltar', participantes_path, class:"btn btn-default" %>

carmapi/app/views/participantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participantes</h1>

<div class="row">
	<table class="table">
	  <thead>
	    <tr>
	      <th>Nome completo</th>
	      <th>Data nascimento</th>
	      <th>Cidade</th>
	      <th>Estado</th>
	      <th>Rg</th>
	      <th>Cpf</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @participantes.each do |participante| %>
	      <tr>
		<td><%= link_to participante.nome_completo, participante %></td>
		<td><%= participante.data_nascimento %></td>
		<td><%= participante.cidade %></td>
		<td><%= participante.estado %></td>
		<td><%= participante.rg %></td>
		<td><%= participante.cpf %></td>
		<td><%= link_to 'Editar', edit_participante_path(participante), class:"btn btn-info" %></td>
		<td><%= link_to 'Deletar', participante, method: :delete, data: { confirm: 'Deseja excluir o participante?' }, class:"btn btn-danger" %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>
<br>

<%= link_to 'Novo Participante',new_participante_path,  class:"btn btn-primary" %>

carmapi/app/views/participantes/new.html.erb
<h1>Cadastros</h1>

<%= render 'form', participante: @participante %>

<br/>
<%= link_to 'Voltar', participantes_path, class:"btn btn-default" %>

carmapi/app/views/participantes/show.html.erb
<div class="container">
	<% if !notice.nil? %>	
		<p id="notice" class="alert alert-success"><%= notice %></p>
	<%end%>
</div>
<div class="container">
    <div class="row">	
	<p>
	  <strong>Nome completo:</strong>
	  <%= @participante.nome_completo %>
	</p>

	<p>
	  <strong>Data nascimento:</strong>
	  <%= @participante.data_nascimento %>
	</p>

	<p>
	  <strong>Cidade:</strong>
	  <%= @participante.cidade %>
	</p>
    </div>
    <div class="row">
	<p>
	  <strong>Estado:</strong>
	  <%= @participante.estado %>
	</p>

	<p>
	  <strong>Rg:</strong>
	  <%= @participante.rg %>
	</p>

	<p>
	  <strong>Cpf:</strong>
	  <%= @participante.cpf %>
	</p>
     </div>
</div>

<hr/>

<%= link_to 'Editar', edit_participante_path(@participante), class:"btn btn-primary" %> 
<%= link_to 'Voltar', participantes_path, class:"btn btn-default" %>